#!/usr/bin/env python3
"""
Unicode Constants for Academic Filename Validation
Extracted from filename_checker.py to reduce file size and improve maintainability
"""

# Superscript character mappings
SUPERSCRIPT_MAP = {
    "0": "\u2070",
    "1": "\u00b9", 
    "2": "\u00b2",
    "3": "\u00b3",
    "4": "\u2074",
    "5": "\u2075",
    "6": "\u2076",
    "7": "\u2077",
    "8": "\u2078",
    "9": "\u2079",
    "a": "\u1d43",
    "b": "\u1d47",
    "c": "\u1d9c",
    "d": "\u1d48",
    "e": "\u1d49",
    "f": "\u1da0",
    "g": "\u1d4d",
    "h": "\u02b0",
    "i": "\u2071",
    "j": "\u02b2",
    "k": "\u1d4f",
    "l": "\u02e1",
    "m": "\u1d50",
    "n": "\u207f",
    "o": "\u1d52",
    "p": "\u1d56",
    "q": "\u1da0",
    "r": "\u02b3",
    "s": "\u02e2",
    "t": "\u1d57",
    "u": "\u1d58",
    "v": "\u1d5b",
    "w": "\u02b7",
    "x": "\u02e3",
    "y": "\u02b8",
    "z": "\u1dbb",
    "A": "\u1d2c",
    "B": "\u1d2e",
    "C": "\u1d9c",
    "D": "\u1d30",
    "E": "\u1d31",
    "F": "\u1da0",
    "G": "\u1d33",
    "H": "\u1d34",
    "I": "\u1d35",
    "J": "\u1d36",
    "K": "\u1d37",
    "L": "\u1d38",
    "M": "\u1d39",
    "N": "\u1d3a",
    "O": "\u1d3c",
    "P": "\u1d3e",
    "Q": "Q",
    "R": "\u1d3f",
    "S": "\u02e2",
    "T": "\u1d40",
    "U": "\u1d41",
    "V": "\u2c7d",
    "W": "\u1d42",
    "X": "\u02e3",
    "Y": "\u02b8",
    "Z": "\u1dbb",
    "+": "\u207a",
    "-": "\u207b",
    "=": "\u207c",
    "(": "\u207d",
    ")": "\u207e",
}

# Subscript character mappings
SUBSCRIPT_MAP = {
    "0": "\u2080",
    "1": "\u2081",
    "2": "\u2082",
    "3": "\u2083",
    "4": "\u2084",
    "5": "\u2085",
    "6": "\u2086",
    "7": "\u2087",
    "8": "\u2088",
    "9": "\u2089",
    "+": "\u208a",
    "-": "\u208b",
    "=": "\u208c",
    "(": "\u208d",
    ")": "\u208e",
    "a": "\u2090",
    "e": "\u2091",
    "h": "\u2095",
    "i": "\u1d62",
    "j": "\u2c7c",
    "k": "\u2096",
    "l": "\u2097",
    "m": "\u2098",
    "n": "\u2099",
    "o": "\u2092",
    "p": "\u209a",
    "r": "\u1d63",
    "s": "\u209b",
    "t": "\u209c",
    "u": "\u1d64",
    "v": "\u1d65",
    "x": "\u2093",
}

# Mathematical blackboard bold mappings
MATHBB_MAP = {
    "A": "\U0001d538",
    "B": "\U0001d539",
    "C": "\u2102",
    "D": "\U0001d53b",
    "E": "\U0001d53c",
    "F": "\U0001d53d",
    "G": "\U0001d53e",
    "H": "\u210d",
    "I": "\U0001d540",
    "J": "\U0001d541",
    "K": "\U0001d542",
    "L": "\U0001d543",
    "M": "\U0001d544",
    "N": "\u2115",
    "O": "\U0001d546",
    "P": "\u2119",
    "Q": "\u211a",
    "R": "\u211d",
    "S": "\U0001d54a",
    "T": "\U0001d54b",
    "U": "\U0001d54c",
    "V": "\U0001d54d",
    "W": "\U0001d54e",
    "X": "\U0001d54f",
    "Y": "\U0001d550",
    "Z": "\u2124",
}

# Number word mappings
NUMBERS = {
    "0": "zero",
    "1": "one",
    "2": "two",
    "3": "three",
    "4": "four",
    "5": "five",
    "6": "six",
    "7": "seven",
    "8": "eight",
    "9": "nine",
}

# Ligature mappings
LIGATURE_MAP = {
    "\ufb00": "ff",
    "\ufb01": "fi",
    "\ufb02": "fl",
    "\ufb03": "ffi",
    "\ufb04": "ffl",
    "\ufb05": "st",
    "\ufb06": "st",
}

# Academic name suffixes
SUFFIXES = [
    "Jr.",
    "Sr.",
    "Jr",
    "Sr",
    "II",
    "III",
    "IV",
    "V",
    "VI",
    "VII",
    "VIII",
    "IX",
    "X",
]

# Conservative ligature whitelist
LIGATURES_WHITELIST = {
    "œuvre": "œuvre",
    "cœur": "cœur",
    "sœur": "sœur",
}

# Mathematical operators and symbols
MATHEMATICAL_OPERATORS = {
    # Comparison operators
    "=", "≠", "≡", "≢", "<", ">", "≤", "≥", "≦", "≧", "≨", "≩",
    "≪", "≫", "≬", "≭", "≮", "≯", "≰", "≱", "≲", "≳", "≴", "≵",
    "≶", "≷", "≸", "≹", "≺", "≻", "≼", "≽", "≾", "≿", "⊀", "⊁",
    "⊂", "⊃", "⊄", "⊅", "⊆", "⊇", "⊈", "⊉", "⊊", "⊋", "⊌", "⊍",
    "⊎", "⊏", "⊐", "⊑", "⊒", "⊓", "⊔", "⊕", "⊖", "⊗", "⊘", "⊙",
    "⊚", "⊛", "⊜", "⊝", "⊞", "⊟", "⊠", "⊡", "⊢", "⊣", "⊤", "⊥",
    "⊦", "⊧", "⊨", "⊩", "⊪", "⊫", "⊬", "⊭", "⊮", "⊯", "⊰", "⊱",
    "⊲", "⊳", "⊴", "⊵", "⊶", "⊷", "⊸", "⊹", "⊺", "⊻", "⊼", "⊽",
    "⊾", "⊿", "⋀", "⋁", "⋂", "⋃", "⋄", "⋅", "⋆", "⋇", "⋈", "⋉",
    "⋊", "⋋", "⋌", "⋍", "⋎", "⋏", "⋐", "⋑", "⋒", "⋓", "⋔", "⋕",
    "⋖", "⋗", "⋘", "⋙", "⋚", "⋛", "⋜", "⋝", "⋞", "⋟", "⋠", "⋡",
    "⋢", "⋣", "⋤", "⋥", "⋦", "⋧", "⋨", "⋩", "⋪", "⋫", "⋬", "⋭",
    "⋮", "⋯", "⋰", "⋱", "⋲", "⋳", "⋴", "⋵", "⋶", "⋷", "⋸", "⋹",
    "⋺", "⋻", "⋼", "⋽", "⋾", "⋿",
    # Arithmetic operators
    "+", "-", "×", "÷", "±", "∓", "∔", "∕", "∖", "∗", "∘", "∙",
    "√", "∛", "∜", "∝", "∞", "∟", "∠", "∡", "∢", "∣", "∤", "∥",
    "∦", "∧", "∨", "∩", "∪", "∫", "∬", "∭", "∮", "∯", "∰", "∱",
    "∲", "∳", "∴", "∵", "∶", "∷", "∸", "∹", "∺", "∻", "∼", "∽",
    "∾", "∿", "≀", "≁", "≂", "≃", "≄", "≅", "≆", "≇", "≈", "≉",
    "≊", "≋", "≌", "≍", "≎", "≏", "≐", "≑", "≒", "≓", "≔", "≕",
    "≖", "≗", "≘", "≙", "≚", "≛", "≜", "≝", "≞", "≟", "≠", "≡",
    # Arrows
    "←", "↑", "→", "↓", "↔", "↕", "↖", "↗", "↘", "↙", "↚", "↛",
    "↜", "↝", "↞", "↟", "↠", "↡", "↢", "↣", "↤", "↥", "↦", "↧",
    "↨", "↩", "↪", "↫", "↬", "↭", "↮", "↯", "↰", "↱", "↲", "↳",
    "↴", "↵", "↶", "↷", "↸", "↹", "↺", "↻", "↼", "↽", "↾", "↿",
    "⇀", "⇁", "⇂", "⇃", "⇄", "⇅", "⇆", "⇇", "⇈", "⇉", "⇊", "⇋",
    "⇌", "⇍", "⇎", "⇏", "⇐", "⇑", "⇒", "⇓", "⇔", "⇕", "⇖", "⇗",
    "⇘", "⇙", "⇚", "⇛", "⇜", "⇝", "⇞", "⇟", "⇠", "⇡", "⇢", "⇣",
    "⇤", "⇥", "⇦", "⇧", "⇨", "⇩", "⇪", "⇫", "⇬", "⇭", "⇮", "⇯",
    "⇰",
    # Mathematical punctuation
    ":", ";", "|", "‖", "∥", "∦", "∝", "∞", "∴", "∵", "∶", "∷",
    "∸", "∹", "∺", "∻", "∼", "∽", "∾", "∿", "≀", "≁", "≂", "≃",
    "≄", "≅", "≆", "≇", "≈", "≉", "≊", "≋", "≌", "≍", "≎", "≏",
    "≐", "≑", "≒", "≓", "≔", "≕", "≖", "≗", "≘", "≙", "≚", "≛",
    "≜", "≝", "≞", "≟", "≠", "≡", "≢", "≣", "≤", "≥", "≦", "≧",
    "≨", "≩", "≪", "≫", "≬", "≭", "≮", "≯", "≰", "≱", "≲", "≳",
    "≴", "≵", "≶", "≷", "≸", "≹", "≺", "≻", "≼", "≽", "≾", "≿",
    # Additional mathematical symbols
    "∮", "∯", "∰", "∱", "∲", "∳",
}

# Greek letters with mathematical variants
MATHEMATICAL_GREEK_LETTERS = {
    # Standard Greek letters
    "α", "β", "γ", "δ", "ε", "ζ", "η", "θ", "ι", "κ", "λ", "μ",
    "ν", "ξ", "ο", "π", "ρ", "σ", "τ", "υ", "φ", "χ", "ψ", "ω",
    "Α", "Β", "Γ", "Δ", "Ε", "Ζ", "Η", "Θ", "Ι", "Κ", "Λ", "Μ",
    "Ν", "Ξ", "Ο", "Π", "Ρ", "Σ", "Τ", "Υ", "Φ", "Χ", "Ψ", "Ω",
    # Mathematical variants
    "ϕ", "ϖ", "ϱ", "ϵ", "ϝ", "ϟ", "ϡ", "ϰ", "ϱ", "ϲ", "ϳ", "ϴ",
    "ϵ", "϶", "Ϸ", "ϸ", "Ϲ", "Ϻ", "ϻ", "ϼ", "Ͻ", "Ͼ", "Ͽ",
}

# German language indicators for context detection
GERMAN_INDICATORS = {
    "deutscher", "deutsche", "deutsches", "untersuchung", "untersuchungen",
    "analyse", "analysen", "theorie", "theorien", "methode", "methoden",
    "funktion", "funktionen", "raum", "räume", "konvergenz", "reihe",
    "reihen", "grenze", "grenzen", "gleichung", "gleichungen", "differential",
    "wahrscheinlichkeit", "stochastisch", "zufällig", "geometrie", "topologie",
    "algebra", "algebraisch", "harmonisch", "integral", "integrale",
    "mathematik", "funktionalanalysis", "differentialgeometrie",
    "wahrscheinlichkeitstheorie", "der", "die", "das", "und", "für",
    "von", "mit", "nach", "bei", "zu", "an", "auf", "über", "unter",
    "durch", "gegen", "ohne", "um", "bis", "seit", "während", "wegen",
    "trotz", "statt", "außer", "binnen", "nicht", "titel", "anführungszeichen",
    "wichtig", "besonders", "müller", "schmidt", "weber", "wagner",
    "becker", "schulz", "hoffmann", "schäfer", "koch", "bauer", "richter",
    "klein", "wolf", "schröder", "allgemein", "allgemeine", "allgemeines",
    "besonder", "besondere", "neu", "neue", "neues", "alt", "alte", "altes",
    "erst", "erste", "zweite", "dritte", "letzte", "einige",
}